simple_model:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
 
  left_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_left_wheel
    pid: {p: 1.0, i: 0.0, d: 1.0}

  right_wheel_controller:
    type: velocity_controllers/JointVelocityController
    joint: joint_right_wheel
    pid: {p: 1.0, i: 0.0, d: 1.0}

